ALTER TABLE schedules ADD COLUMN IF NOT EXISTS type VARCHAR(50) NOT NULL DEFAULT 'scheduled';
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS account_type VARCHAR(50) NOT NULL DEFAULT 'static';
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS account_details JSONB;
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS provision_status VARCHAR(50) NOT NULL DEFAULT 'pending';
